# wordpress/wordpress-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: gcr.io/mounika8036-426015/wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb.mariadb.svc.cluster.local
        - name: WORDPRESS_DB_USER
          value: myuser
        - name: WORDPRESS_DB_PASSWORD
          value: mypassword
        - name: WORDPRESS_DB_NAME
          value: mydb  
        ports:
        - containerPort: 80
